import type { AutodeskApp } from './types';

export const autodeskApps: AutodeskApp[] = [
  { id: 'autocad', name: 'AutoCAD' },
  { id: 'revit', name: 'Revit' },
  { id: 'fusion360', name: 'Fusion 360' },
  { id: 'maya', name: 'Maya' },
  { id: '3dsmax', name: '3ds Max' },
  { id: 'civil3d', name: 'Civil 3D' },
  { id: 'inventor', name: 'Inventor' },
  { id: 'autocad-lt', name: 'AutoCAD LT' },
  { id: 'navisworks-manage', name: 'Navisworks Manage' },
  { id: 'arnold', name: 'Arnold' },
  { id: 'bim-360', name: 'BIM 360' },
  { id: 'construction-cloud', name: 'Construction Cloud' },
  { id: 'formit-pro', name: 'FormIt Pro' },
  { id: 'infraworks', name: 'InfraWorks' },
  { id: 'motionbuilder', name: 'MotionBuilder' },
  { id: 'mudbox', name: 'Mudbox' },
  { id: 'recap-pro', name: 'ReCap Pro' },
  { id: 'robot-structural-analysis', name: 'Robot Structural Analysis Professional' },
  { id: 'sketchbook', name: 'SketchBook' },
  { id: 'alias-autostudio', name: 'Alias AutoStudio' },
  { id: 'vred-professional', name: 'VRED Professional' },
  { id: 'powermill', name: 'PowerMill' },
  { id: 'powershape', name: 'PowerShape' },
  { id: 'powerinspect', name: 'PowerInspect' },
  { id: 'featurecam', name: 'FeatureCAM' },
  { id: 'netfabb', name: 'Netfabb' },
  { id: 'moldflow-adviser', name: 'Moldflow Adviser' },
  { id: 'moldflow-insight', name: 'Moldflow Insight' },
  { id: 'cfd', name: 'CFD' },
  { id: 'vault', name: 'Vault' },
  { id: 'fabrication-cadmep', name: 'Fabrication CADmep' },
  { id: 'fabrication-camduct', name: 'Fabrication CAMduct' },
  { id: 'fabrication-estmep', name: 'Fabrication ESTmep' },
  { id: 'point-layout', name: 'Point Layout' },
  { id: 'advance-steel', name: 'Advance Steel' },
  { id: 'revit-lt-suite', name: 'Revit LT Suite' },
  { id: 'buildingconnected', name: 'BuildingConnected' },
  { id: 'plangrid', name: 'PlanGrid' },
  { id: 'pype', name: 'Pype' },
  { id: 'assemble', name: 'Assemble' },
  { id: 'shotgrid', name: 'ShotGrid' },
  { id: 'tinkercad', name: 'Tinkercad' },
  { id: 'character-generator', name: 'Character Generator' },
  { id: 'meshmixer', name: 'Meshmixer' },
  { id: 'eagle', name: 'Eagle' },
];
