import type { AutodeskApp } from './types';

export const autodeskApps: AutodeskApp[] = [
  { id: 'tinkercad', name: 'Tinkercad' },
  { id: 'fusion-360', name: 'Fusion 360' },
  { id: 'revit', name: 'Revit' },
  { id: 'revit-generative-design', name: 'Revit Generative Design' },
  { id: 'autocad', name: 'Autocad' },
  { id: 'autocad-for-mac', name: 'Autocad for Mac' },
  { id: 'autocad-web', name: 'Autocad Web' },
  { id: 'inventor-professional', name: 'Inventor Professional' },
  { id: '3ds-max', name: '3Ds Max' },
  { id: 'maya', name: 'Maya' },
  { id: 'advance-steel', name: 'Advance Steel' },
  { id: 'alias-autostudio', name: 'Alias Autostudio' },
  { id: 'arnold', name: 'Arnold' },
  { id: 'autocad-lt', name: 'Autocad LT' },
  { id: 'autocad-lt-for-mac', name: 'Autocad LT for Mac' },
  { id: 'autodesk-cfd-ultimate', name: 'Autodesk CFD Ultimate' },
  { id: 'civil-3d', name: 'Civil 3D' },
  { id: 'civil-3d-project-explorer', name: 'Civil 3D Project Explorer' },
  { id: 'civil-3d-grading-optimization', name: 'Civil 3D Grading Optimization' },
  { id: 'fabrication-cadmep', name: 'Fabrication CADmep' },
  { id: 'fabrication-camduct', name: 'Fabrication CAMduct' },
  { id: 'fabrication-estmep', name: 'Fabrication ESTmep' },
  { id: 'factory-design-utility', name: 'Factory Design Utility' },
  { id: 'featurecam', name: 'FeatureCAM' },
  { id: 'flame', name: 'Flame' },
  { id: 'autodesk-forma', name: 'Autodesk Forma' },
  { id: 'formit', name: 'Formit' },
  { id: 'formit-pro', name: 'Formit Pro' },
  { id: 'hsmworks-ultimate', name: 'HSMWorks Ultimate' },
  { id: 'infraworks', name: 'Infraworks' },
  { id: 'inventor-cam', name: 'Inventor CAM' },
  { id: 'inventor-nastran', name: 'Inventor Nastran' },
  { id: 'inventor-nesting', name: 'Inventor Nesting' },
  { id: 'inventor-tolerance-analysis', name: 'Inventor Tolerance Analysis' },
  { id: 'motionbuilder', name: 'MotionBuilder' },
  { id: 'mudbox', name: 'Mudbox' },
  { id: 'navisworks-manage', name: 'Navisworks Manage' },
  { id: 'netfabb-premium', name: 'Netfabb Premium' },
  { id: 'point-layout', name: 'Point Layout' },
  { id: 'powerinspect', name: 'PowerInspect' },
  { id: 'powershape', name: 'PowerShape' },
  { id: 'recap-pro', name: 'Recap Pro' },
  { id: 'robot-structural-analysis-professional', name: 'Robot Structural Analysis Professional' },
  { id: 'structural-bridge-design', name: 'Structural Bridge Design' },
  { id: 'vehicle-tracking', name: 'Vehicle Tracking' },
  { id: 'vred-professional', name: 'Vred Professional' },
];
